### ISSUE TITLE
登录不了

### ISSUE THREAD

**Issue by MyLittleStone** [WeChatAPIs/WeChatApi#5]
登录不了
![image](https://github.com/WeChatAPIs/WeChatApi/assets/12386511/1364f698-d120-4441-9fb0-eb6ebb951ab9)
![image](https://github.com/WeChatAPIs/WeChatApi/assets/12386511/5c40e395-85ad-4019-b7b8-c29d406ba433)

**Comment by WeChatAPIs** [comment]
文档有写支持的系统，技术支持群也不是这里 ！
